<?php

namespace GestionPfeBundle\Repository;

/**
 * centresInteretsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class centresInteretsRepository extends \Doctrine\ORM\EntityRepository
{
}
