<?php

namespace GestionPfeBundle\Repository;

/**
 * CompetencesTechniquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetencesTechniquesRepository extends \Doctrine\ORM\EntityRepository
{
}
