<?php

namespace GestionPfeBundle\Repository;

/**
 * EncadrementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncadrementRepository extends \Doctrine\ORM\EntityRepository
{
}
