<?php

namespace GestionPfeBundle\Repository;

/**
 * formationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class formationsRepository extends \Doctrine\ORM\EntityRepository
{
}
