<?php

namespace GestionPfeBundle\Repository;

/**
 * languesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class languesRepository extends \Doctrine\ORM\EntityRepository
{
}
