<?php

namespace GestionPfeBundle\Repository;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOffre()
    {
        $query = $this->getEntityManager()->createQuery("SELECT DISTINCT (o.idUser) FROM GestionPfeBundle:Offre o ");

        return $query->getResult();
    }
}
