<?php

namespace GestionPfeBundle\Repository;

/**
 * SoutenanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoutenanceRepository extends \Doctrine\ORM\EntityRepository
{
}
