<?php

namespace GestionPfeBundle\Repository;

/**
 * StageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageRepository extends \Doctrine\ORM\EntityRepository
{
    public function AllStagesNoEncadrant()
    {
        $query=$this->getEntityManager()
            ->createQuery("
        select s from GestionPfeBundle:Stage s where s.idEncadrant is NULL ");
        return $query->getResult();
    }
    public function AllEncadrant()
    {
        $query=$this->getEntityManager()
            ->createQuery("
        select a from GestionPfeBundle:User a where a.roles = 'ROLE_ENSEIGNANT' ");
        return $query->getResult();
    }
}
