<?php

namespace GestionPfeBundle\Repository;

/**
 * technolgiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class technolgiesRepository extends \Doctrine\ORM\EntityRepository
{
}
